### ISSUE TITLE
Decking 0.4.0 (next preview release) task list

### ISSUE THREAD

**Issue by makeusabrew** [meetfinch/decking#82]
**Definitely**

 - [x] First class data containers (#56)
 - [x] Stop using `docker run` when running `decking create` (#31)
 - [ ] Make `decking start` simply create missing containers instead of erroring
 - [x] `decking destroy` (#4)
 - [x] optional custom tag when building images (#53)
 - [x] add `--as` alias when managing grouped clusters

**Maybe**
 - [x] friendlier non-TTY output
 - [ ] tabularised `decking status` output
 - [x] optional `ready` parameter (#21)
 - [x] support `-c` and `-m` (#83)

Release date: On or before Saturday 21st February 2015.

**Comment by makeusabrew** [comment]
0.4.0 now available :)
